services:
  expense-web:
    container_name: expense-web
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    ports:
      - 8080:3000
    environment:
      - VITE_APP_EXPENSE_API_URL=https://api.expense.gomes.dev/expenses
