# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Expense API - Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CONTAINER_NAME: ${{ github.repository }}

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Generate container name
        id: container-name
        run: |
          container_name="${{ env.CONTAINER_NAME }}-api"
          echo "INTERNAL_CONTAINER_NAME=$container_name" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%Y.%-m.%-d.%-H.%-M.%-S')" # this is the build number of our image as date

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push the image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./expense-api
          file: ./expense-api/Dockerfile
          push: true
          tags: |
            ${{ env.INTERNAL_CONTAINER_NAME }}:${{ steps.build-number.outputs.BUILD_NUMBER }}
            ${{ env.INTERNAL_CONTAINER_NAME }}:latest

  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Generate container name
        id: container-name
        run: |
          container_name="${{ env.CONTAINER_NAME }}-web"
          echo "INTERNAL_CONTAINER_NAME=$container_name" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%Y.%-m.%-d.%-H.%-M.%-S')" # this is the build number of our image as date

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push the image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./expense-web
          file: ./expense-web/Dockerfile
          push: true
          tags: |
            ${{ env.INTERNAL_CONTAINER_NAME }}:${{ steps.build-number.outputs.BUILD_NUMBER }}
            ${{ env.INTERNAL_CONTAINER_NAME }}:latest
