# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Expense Web - Deploy

on:
  push:
    branches: ["main"]
    paths:
      - expense-web/**
      - .github/workflows/deploy-web.yml
  workflow_dispatch:

env:
  CONTAINER_NAME: ${{ github.repository }}-web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%Y.%-m.%-d.%-H.%-M.%-S')" # this is the build number of our image as date

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push the image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./expense-web
          file: ./expense-web/Dockerfile
          push: true
          tags: |
            ${{ env.CONTAINER_NAME }}:${{ steps.build-number.outputs.BUILD_NUMBER }}
            ${{ env.CONTAINER_NAME }}:latest
